name: Doxygen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: tqfx/scripts
        run: git clone https://github.com/tqfx/scripts.git gh-scripts

      - name: Setup
        shell: bash
        run: |
          bash gh-scripts/apt-doxygen.sh

      - name: Build
        shell: bash
        run: |
          doxygen doxygen/Doxyfile

      - name: Deploy
        shell: bash
        env:
          COMMIT_GPG_KEY: ${{ secrets.COMMIT_GPG_KEY }}
          COMMIT_GPG_ID: ${{ secrets.COMMIT_GPG_ID }}
          BRANCH: gh-pages
        run: |
          bash gh-scripts/gh-config.sh
          bash gh-scripts/gh-deploy.sh html

