
name: klib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "59302530+tqfx@users.noreply.github.com"
          git config --global core.autocrlf input
          git config --global core.quotepath false
          git config --global core.filemode false
          git config --global core.ignorecase false
      - name: Push
        run: |
          bash -c 'for i in `ls -A`; do \
          if [ "$i" == ".git" ]; then continue; fi;\
          if [ "$i" == "klib" ]; then continue; fi;\
          rm -rf $i; echo "rm -rf $i"; done'
          bash -c 'for i in `ls -A klib`; do \
          mv -t . klib/$i; echo "mv -t . klib/$i"; done'
          rmdir klib
          git checkout -q --orphan klib
          git add -A
          git commit -s -q -m $(git rev-parse origin/master)
          git push -f origin klib
          git checkout -
          git branch -D klib
