name: release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          library: klib
        run: |
          echo "remove..."
          bash -c 'for i in `ls -A`; do \
          if [ "$i" == ".git" ]; then continue; fi;\
          if [ "$i" == "$library" ]; then continue; fi;\
          rm -rf $i; done'
          echo "move..."
          bash -c 'for i in `ls -A $library`; do \
          mv -t . $library/$i; done'
          rmdir $library

      - name: Config
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "59302530+tqfx@users.noreply.github.com"
          git config --global core.autocrlf input
          git config --global core.quotepath false
          git config --global core.filemode false
          git config --global core.ignorecase false
          git config --list

      - name: Push
        env:
          branch: release
        run: |
          git checkout --quiet --orphan $branch
          git add --all
          git commit --quiet --signoff --message $(git rev-parse origin/master)
          git push --force origin $branch
